# Generated by Django 6.0.4 on 2026-04-10 19:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='e.g., A-101', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Unit number must contain only letters, numbers, and hyphens', regex='^[A-Z0-9\\-]+$')])),
                ('block', models.CharField(max_length=50)),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('area_sqft', models.DecimalField(decimal_places=2, help_text='Carpet area in square feet', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Shop', 'Shop'), ('Office', 'Office'), ('Parking', 'Parking')], default='Flat', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Disputed', 'Disputed'), ('Sold', 'Sold'), ('Vacant', 'Vacant')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Units',
                'ordering': ['block', 'floor', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('occupant_type', models.CharField(choices=[('Family Member', 'Family Member'), ('Tenant', 'Tenant'), ('Caretaker', 'Caretaker'), ('Guest', 'Guest')], default='Family Member', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='units.unit')),
            ],
            options={
                'ordering': ['unit', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('occupant_type', models.CharField(choices=[('Owner', 'Owner'), ('Tenant', 'Tenant'), ('Caretaker', 'Caretaker'), ('Co-owner', 'Co-owner')], default='Owner', max_length=20)),
                ('contact_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('alternate_contact', models.CharField(blank=True, max_length=15)),
                ('membership_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Left', 'Left')], default='Active', max_length=20)),
                ('payment_preference', models.CharField(choices=[('Online', 'Online Transfer'), ('Check', 'Check'), ('Cash', 'Cash'), ('Auto-Debit', 'Auto-Debit')], default='Online', max_length=20)),
                ('bank_account', models.JSONField(blank=True, default=dict, help_text='Store as JSON: {account_holder, account_no, ifsc, bank_name}')),
                ('share_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Ownership percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_primary', models.BooleanField(default=True, help_text='Primary contact for the unit')),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('nominated_person_name', models.CharField(blank=True, max_length=200)),
                ('nominated_person_contact', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_updated', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='units.unit')),
            ],
            options={
                'ordering': ['unit', 'owner_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Unit', 'Unit'), ('Member', 'Member')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('entity_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-changed_at'], name='units_audit_entity__f974ca_idx'), models.Index(fields=['-changed_at'], name='units_audit_changed_1e7a73_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_number'], name='units_unit_unit_nu_26d2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['block', 'floor'], name='units_unit_block_96e190_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='units_unit_status_08f0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['unit'], name='units_membe_unit_id_3a3e87_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['owner_name'], name='units_membe_owner_n_553ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['contact_email'], name='units_membe_contact_69b09d_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['contact_phone'], name='units_membe_contact_0a6657_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_status'], name='units_membe_members_b0a95b_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('unit', 'is_primary'), name='unique_primary_member_per_unit'),
        ),
    ]
