# Generated by Django 6.0.4 on 2026-04-11 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin / Society Secretary'), ('Treasurer', 'Treasurer / Accountant'), ('Member', 'Resident / Member'), ('Board Member', 'Board Member'), ('Auditor', 'Auditor')], default='Member', max_length=30)),
                ('portal_access', models.BooleanField(default=True, help_text='Allow portal access for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(blank=True, help_text='Optional member record linked to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='units.member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['role'], name='units_userp_role_4d64a3_idx')],
            },
        ),
    ]
