# Generated by Django 6.0.4 on 2026-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_invoicedeletionapprovaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='invoice_frequency',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Annual', 'Annual')], default='', help_text='Override maintenance invoice frequency for this unit. Leave blank to use template default.', max_length=20),
        ),
    ]
