# Generated by Django 6.0.4 on 2026-04-19 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_rename_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FormatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number_format', models.CharField(default='INV-[fiscal_year]-[seq]', max_length=255)),
                ('invoice_seq_digits', models.PositiveIntegerField(default=4)),
                ('invoice_seq_start', models.PositiveIntegerField(default=1)),
                ('invoice_seq_next', models.PositiveIntegerField(default=1)),
                ('receipt_number_format', models.CharField(default='RCPT-[fiscal_year]-[seq]', max_length=255)),
                ('receipt_seq_digits', models.PositiveIntegerField(default=4)),
                ('receipt_seq_start', models.PositiveIntegerField(default=1)),
                ('receipt_seq_next', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Format Settings',
                'verbose_name_plural': 'Format Settings',
            },
        ),
    ]
