# Generated by Django 6.0.4 on 2026-04-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_invoice_invoice_number_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='share_amount',
        ),
    ]
